<script src="{{ asset('frontend/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('frontend/js/salvattore.min.js') }}"></script>
<script src="{{ asset('frontend/js/slick.min.js') }}"></script>
<script src="{{ asset('frontend/js/panel.js') }}"></script>
<script src="{{ asset('frontend/js/reading-position-indicator.js') }}"></script>
<script src="{{ asset('frontend/js/rrssb.min.js') }}"></script>
<!-- <script src="{{ asset('frontend/js/featherlight.js') }}"></script> -->
 <!-- <script src="https://cdn.jsdelivr.net/npm/featherlight@1.7.14/release/featherlight.gallery.min.js"></script> -->
<script src="{{ asset('frontend/js/custom.js') }}"></script>